name: M+ Requirement Check

on:
  schedule:
    # Runs every Monday at 08:00 UTC
    # Adjust cron schedule as needed (e.g., '0 8 * * 1' for Monday 8 AM UTC)
    # You can use https://crontab.guru/ to help generate schedules.
    - cron: '0 8 * * 1'
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub UI

jobs:
  check_requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' # Use the latest Python 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run M+ Requirement Script
        run: python check_mplus_requirements.py
        env:
           IMPORTANT: Store your Discord Webhook URL as a repository secret
           Go to your GitHub repo -> Settings -> Secrets and variables -> Actions -> New repository secret
           Name it DISCORD_WEBHOOK_URL and paste your webhook URL there.
           Then, in your Python script, you'd retrieve it using os.getenv('DISCORD_WEBHOOK_URL')
           For this example, it's directly in the Python script, but secrets are best practice.
           DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
