name: M+ Requirement Check (Current Period)

on:
  schedule:
    # Runs every Monday at 08:00 UTC (10:00 Danish time)
    #- cron: '0 8 * * 1' # Monday 10:00 Dansk Tid
    #- cron: '*/5 * * * *'
  workflow_dispatch:
    # Allows you to manually trigger this specific workflow from the GitHub UI

jobs:
  check_current_period:
    runs-on: ubuntu-latest
    # Add permissions for the workflow to write to the repository
    permissions:
      contents: write # This grants permission to write files to the repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # This action uses the GITHUB_TOKEN to check out the repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script for Current Period
        run: python check_mplus_requirements.py
        env:
          WOWAUDIT_API_KEY: ${{ secrets.WOWAUDIT_API_KEY }}
          #DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL_CURRENT_PERIOD }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          USE_PREVIOUS_PERIOD: 'false'
          PERIOD_TYPE: 'current'
