name: M+ Requirement Check (Current Period)

on:
  schedule:
    # Example: Runs every Tuesday at 18:00 UTC (20:00 Danish time)
    # Adjust cron schedule as needed
    - cron: '0 8 * * 1' # Tuesday 20:00 Danish Time
  workflow_dispatch:
    # Allows you to manually trigger this specific workflow from the GitHub UI

jobs:
  check_current_period:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script for Current Period
        run: python check_mplus_requirements.py
        env:
          WOWAUDIT_API_KEY: ${{ secrets.WOWAUDIT_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          USE_PREVIOUS_PERIOD: 'false' # Tell the Python script to use current_period (or omit this line, 'false' is default)
